import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useContext } from 'react'
import ReactHTMLTableToExcel from 'react-html-table-to-excel'
import Layout from '../components/Layout'
import Table from '../components/Table'
import {UsersContext} from '../UsersContext'
import styles from '../styles/Form.module.css'
import Buscador from '../components/Buscador'

export default function Home() {
  const {users, setUsers} = useContext(UsersContext)
  const router = useRouter()

  useEffect(() => {
    const getUsers = async () => {
      const {data} = await axios({
        method: 'GET',
        url: '/api/reports',
      })
      setUsers(data)
    }
    getUsers()

  }, [setUsers])


  return (
    <Layout>
      <Head>
        <title>Reportes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Buscador users={users} setUsers={setUsers} url={'reports'} />
      <div style={{display: 'flex', width: '100%'}}>
        <ReactHTMLTableToExcel 
          id='exportarAExcel'
          table='usuarios'
          className={styles.excel}
          filename='ReporteGeneral'
          sheet='pagina 1'
          buttonText='Exportar a Excel'
        />
      <button 
        onClick={() => router.push('/print')}
        className={styles.button}
      >
        Imprimir Reportes
      </button>
      </div>
      <Table users={users} id='usuarios' />
    </Layout>
  )
}
