import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useContext, useState } from 'react'
import ReactHTMLTableToExcel from 'react-html-table-to-excel'
import Layout from '../components/Layout'
import Table from '../components/Table'
import {UsersContext} from '../UsersContext'
import styles from '../styles/Form.module.css'
import Buscador from '../components/Buscador'
import {getUsers} from '../helpers'
const jwt = require('jsonwebtoken')


export default function Home() {
  const {setUsers} = useContext(UsersContext)
  const [filtro, setFiltro] = useState([])
  const router = useRouter()


  useEffect(() => {
    const token = localStorage.getItem('token')

    if (!token) {
      router.replace('/login')
    } else {
      jwt.verify(token, process.env.NEXT_PUBLIC_SECRET, function(err, decoded) {
        if (err) {
          router.push('/login')
        }
      })

      getUsers()
        .then(data => {
          setUsers(data)
          setFiltro(data.filter(({ date }) => {
            return new Date(date).toLocaleDateString() === new Date().toLocaleDateString()
          }))
        })
    }

  }, [setUsers, setFiltro])



  return (
    <Layout>
      <Head>
        <title>Reportes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Buscador users={filtro} setUsers={setFiltro} id={'reports'} />
      <div style={{display: 'flex', width: '100%'}}>
        <ReactHTMLTableToExcel 
          id='exportarAExcel'
          table='usuarios'
          className={styles.excel}
          filename='ReporteGeneral'
          sheet='pagina 1'
          buttonText='Exportar a Excel'
        />
      <button 
        onClick={() => router.push('/print')}
        className={styles.button}
      >
        Imprimir Reportes
      </button>
      </div>
      <Table users={filtro} id='usuarios' />
    </Layout>
  )
}
