import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Layout from '../components/Layout'
import Table from '../components/Table'
import Buscador from '../components/Buscador'
import {Pagination} from '@material-ui/lab'

export default function Reportes() {

  const perPage = 15
  const [allUsers, setAllUsers] = useState([])
  const [page, setPage] = useState(1)
  const [filtro, setFiltro] = useState(allUsers?.slice((page-1) * perPage, page * perPage))
  const count = Math.ceil(allUsers.length / perPage)

  const handleChange = (event, value) => {
    setPage(value)
    setFiltro(allUsers.slice((value-1) * perPage, value * perPage))
  }
  useEffect(() => {
    const getUsers = async () => {
      const {data} = await axios({
        method: 'GET',
        url: '/api/reportes',
      })
      setAllUsers(data)
    }
    getUsers()

  }, [setAllUsers])


  return (
    <Layout>
      <Head>
        <title>Reportes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Buscador users={allUsers} setUsers={setAllUsers} url={'reportes'} />
      <Pagination count={count} page={page} onChange={handleChange} variant="outlined" shape="rounded" />
      <Table users={filtro} />
      <Pagination count={count} page={page} onChange={handleChange} variant="outlined" shape="rounded" />
    </Layout>
  )
}
