import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'
import {Pagination} from '@material-ui/lab'
import Layout from '../components/Layout'
import Table from '../components/Table'
import Buscador from '../components/Buscador'
import {UsersContext} from '../UsersContext'
import {getUsers} from '../helpers'
import {useRouter} from 'next/router'
const jwt = require('jsonwebtoken')

export default function Reportes() {
  const { users, setUsers } = useContext(UsersContext)
  
  const perPage = 20
  const [page, setPage] = useState(1)

  const [filtro, setFiltro] = useState(users.slice((page-1) * perPage, page * perPage))

  const count = Math.ceil(users.length / perPage)

  const router = useRouter()

  const handleChange = (event, value) => {
    setPage(value)
    setFiltro(users.slice((value-1) * perPage, value * perPage))
  }

  useEffect(() => {
    const token = localStorage.getItem('token')

    if (!token) {
      router.replace('/login')
    } else {
      jwt.verify(token, process.env.NEXT_PUBLIC_SECRET, function(err, decoded) {
        if (err) {
          router.replace('/login')
        }
      })
    }
  })
  
  useEffect(() => {

    if (users.length === 0) {
      getUsers()
        .then(data => setUsers(data))
    }
  }, [users, setUsers])

  return (
    <Layout>
      <Head>
        <title>Reportes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Buscador
        users={users} 
        setUsers={setFiltro} 
        id={'reportes'} 
        page={page}
        perPage={perPage}
      />
      <Pagination count={count} page={page} onChange={handleChange} variant="outlined" shape="rounded" />
      <Table users={filtro} />
      <Pagination count={count} page={page} onChange={handleChange} variant="outlined" shape="rounded" />
    </Layout>
  )
}
