import axios from 'axios'
import Head from 'next/head'
import { useContext, useState } from 'react'
import {Pagination} from '@material-ui/lab'
import Layout from '../components/Layout'
import Table from '../components/Table'
import Buscador from '../components/Buscador'
import {UsersContext} from '../UsersContext'

export default function Reportes() {
  const { users } = useContext(UsersContext)
  
  const perPage = 20
  const [page, setPage] = useState(1)

  const [filtro, setFiltro] = useState(users.slice((page-1) * perPage, page * perPage))

  const count = Math.ceil(users.length / perPage)

  const handleChange = (event, value) => {
    setPage(value)
    setFiltro(users.slice((value-1) * perPage, value * perPage))
  }

  return (
    <Layout>
      <Head>
        <title>Reportes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Buscador
        users={users} 
        setUsers={setFiltro} 
        id={'reportes'} 
        page={page}
        perPage={perPage}
      />
      <Pagination count={count} page={page} onChange={handleChange} variant="outlined" shape="rounded" />
      <Table users={filtro} />
      <Pagination count={count} page={page} onChange={handleChange} variant="outlined" shape="rounded" />
    </Layout>
  )
}
